anken/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('accounts/', include('accounts.urls')),
    path('cms/', include('cms.urls')),
    path('admin/', admin.site.urls),
]

cms/urls.py
from django.urls import path
from cms import views


app_name = 'cms'
urlpatterns = [
    path('top/', views.top, name='top'),
    path('anken/', views.anken_list, name='anken_list'),
    path('task/', views.task, name='task'),
    path('anken/archiveanken/', views.archiveanken_list, name='archiveanken_list'),
    path('anken/weekanken/', views.weekanken_list, name='weekanken_list'),
    path('anken/add/', views.anken_edit, name='anken_add'),
    path('anken/mod/<int:anken_id>/', views.anken_edit, name='anken_mod'),
    path('anken/archive/<int:anken_id>/', views.anken_archive, name='anken_archive'),
    path('anken/archiveback/<int:anken_id>/', views.anken_archiveback, name='anken_archiveback'),
    path('anken/del/<int:anken_id>/', views.anken_del, name='anken_del'),


    path('sintyoku/<int:anken_id>/', views.SintyokuList.as_view(), name='sintyoku_list'),  # 一覧
    path('sintyoku/add/<int:anken_id>/', views.sintyoku_edit, name='sintyoku_add'),        # 登録
    path('task/add/<int:anken_id>/', views.task_edit, name='task_add'),        # 登録
    path('sintyoku/mod/<int:anken_id>/<int:sintyoku_id>/', views.sintyoku_edit, name='sintyoku_mod'),  # 修正
    path('sintyoku/del/<int:anken_id>/<int:sintyoku_id>/', views.sintyoku_del, name='sintyoku_del'),   # 削除


    path('task/top', views.task_top, name='task_top'),

]

cms/models.py
from django.db import models
from django.utils import timezone
# Create your models here.


class Anken(models.Model):
    enduser = models.CharField('E/U', max_length=255)
    hansha = models.CharField('販社', max_length=255)
    product = models.CharField('プロダクト', max_length=255)
    sbkk = models.CharField('SBKKトスアップ', max_length=255, blank=True)
    hansui = models.CharField('販推', max_length=255, blank=True)
    sisuisin = models.CharField('SI推進', max_length=255)
    hitouch = models.CharField('ハイタッチ担当', max_length=255, blank=True)
    donyusien = models.CharField('導入支援', max_length=255, blank=True)
    jutyu = models.DateField('受注時期', blank=False)
    donyu = models.DateField('導入時期', blank=False)
    kakudo = models.CharField('確度', max_length=255, blank=True)
    kyougou = models.CharField('競合', max_length=255, blank=True)
    kousinjikoku = models.DateField(verbose_name='', blank=True, null=True, auto_now=True)
    archiveflag = models.BooleanField(verbose_name='', default=False)
    mitumorigaku = models.DecimalField('見積もり金額', max_digits=10, decimal_places=0, blank=True, null=True)
    arari = models.DecimalField('粗利額', max_digits=10, decimal_places=0, blank=True, null=True)
    joukyo = models.CharField('状況', max_length=255, blank=True)

    def __str__(self):
        return self.enduser


class Sintyoku(models.Model):
    sintyoku = models.ForeignKey(Anken, verbose_name='案件', related_name='sintyokus', on_delete=models.CASCADE)
    kinyubi = models.DateField('記入日', blank=True, default=timezone.now)
    shosai = models.TextField('進捗内容', blank=True)

    def __str__(self):
        return self.shosai


class Todo(models.Model):
    todo = models.ForeignKey(Anken, verbose_name='案件', related_name='todos', on_delete=models.CASCADE)
    kanryoflg = models.BooleanField(verbose_name='', default=False)
    task = models.TextField('タスク', blank=True)
    kigen = models.DateField('期限', blank=True)

    def __str__(self):
        return self.todo


class Task(models.Model):
    anken = models.ForeignKey(Anken, verbose_name='案件', related_name='tasks', on_delete=models.CASCADE)
    kanryoflg = models.BooleanField(verbose_name='', default=False)
    task = models.TextField('タスク', blank=True)
    kigen = models.DateField('期限', blank=True)
    tantou = models.CharField('担当', max_length=255, blank=True)

    def __str__(self):
        return self.task

cms/forms.py
from django.forms import ModelForm
from cms.models import Anken, Sintyoku, Todo, Task
from django import forms

class AnkenForm(ModelForm):
    """案件のフォーム"""
    class Meta:
        model = Anken
        fields = ('enduser', 'hansha', 'joukyo', 'product', 'sbkk', 'hansui', 'sisuisin', 'hitouch', 'donyusien', 'jutyu', 'donyu', 'kakudo', 'kyougou', 'mitumorigaku', 'arari', )
        """日付の入力をプルダウンで。"""
        widgets = {
            'jutyu': forms.SelectDateWidget(years=[x for x in range(2019, 2030)]),
            'donyu': forms.SelectDateWidget(years=[x for x in range(2019, 2030)])
        }


class SintyokuForm(ModelForm):
    """進捗のフォーム"""
    class Meta:
        model = Sintyoku
        fields = ('kinyubi', 'shosai', )

class TodoForm(forms.ModelForm):
    """Todoのフォーム"""
    class Meta:
        model = Todo
        fields = ('kanryoflg', 'task', 'kigen',)



class TaskForm(forms.ModelForm):
    """Taskのフォーム"""
    class Meta:
        model = Task
        fields = ('kanryoflg', 'task', 'kigen', 'tantou',)

cms/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponse
from cms.models import Anken, Sintyoku, Todo, Task
from cms.forms import AnkenForm, SintyokuForm, TodoForm, TaskForm
from django.views.generic.list import ListView
from django.utils import timezone
from datetime import date, datetime
from django.views import generic
# Create your views here.

def top(request):
    return render(request,
                  'cms/top.html')


def anken_list(request):
    """案件一覧"""
    # return HttpResponse('案件一覧')
    # ankens = Anken.objects.all().order_by('jutyu')
    ankens = Anken.objects.filter(archiveflag=False).order_by('kousinjikoku').reverse
    return render(request,
                  'cms/anken_list.html',
                  {'ankens': ankens})

def task(request):
    return render(request,
                  'cms/task.html')


def task_top(request):
    tasks = Task.objects.order_by('id').reverse
    return render(request,
                  'cms/task_top.html',
                  {'tasks': tasks})



def archiveanken_list(request):
    """過去案件一覧"""
    # return HttpResponse('案件一覧')
    # ankens = Anken.objects.all().order_by('jutyu')
    ankens = Anken.objects.filter(archiveflag=True).order_by('jutyu')
    return render(request,
                  'cms/archiveanken_list.html',
                  {'ankens': ankens})


def weekanken_list(request):
    """1週間案件一覧"""
    # return HttpResponse('案件一覧')
    # ankens = Anken.objects.all().order_by('jutyu')
    ankens = Anken.objects.filter(archiveflag=True).filter(kousinjikoku__icontains=date.today()).order_by('kousinjikoku').reverse
    # ankens = Anken.objects.filter(archiveflag=False).order_by('kousinjikoku').reverse


    return render(request,
                  'cms/weekanken_list.html',
                  {'ankens': ankens})


def anken_edit(request, anken_id=None):
    """案件の編集"""
    # return HttpResponse('案件の編集')
    if anken_id:
        anken = get_object_or_404(Anken, pk=anken_id)
    else:
        anken = Anken()

    if request.method == 'POST':
        form = AnkenForm(request.POST, instance=anken)
        if form.is_valid():
            anken = form.save(commit=False)
            anken.save()
            return redirect('cms:anken_list')
    else:
        form = AnkenForm(instance=anken)

    return render(request, 'cms/anken_edit.html', dict(form=form, anken_id=anken_id))


def anken_del(request, anken_id):
    """案件の削除"""
    # return HttpResponse('案件の削除')
    anken = get_object_or_404(Anken, pk=anken_id)
    anken.delete()
    return redirect('cms:anken_list')


def anken_archive(request, anken_id):
    """案件のアーカイブ"""
    anken = get_object_or_404(Anken, pk=anken_id)
    anken.archiveflag = True
    anken.save()
    return redirect('cms:anken_list')


def anken_archiveback(request, anken_id):
    """案件のアーカイブ"""
    anken = get_object_or_404(Anken, pk=anken_id)
    anken.archiveflag = False
    anken.save()
    return redirect('cms:anken_list')


class SintyokuList(ListView):
    context_object_name = 'sintyokus'
    template_name = 'cms/sintyoku_list.html'
    paginate_by = 10

    def get(self, request, *args, **kwargs):
        anken = get_object_or_404(Anken, pk=kwargs['anken_id'])
        sintyokus = anken.sintyokus.all().order_by('-kinyubi')
        self.object_list = sintyokus

        context = self.get_context_data(object_list=self.object_list, anken=anken)
        return self.render_to_response(context)



def sintyoku_edit(request, anken_id, sintyoku_id=None):
    """進捗の編集"""
    anken = get_object_or_404(Anken, pk=anken_id)  # 親の書籍を読む
    if sintyoku_id:   # impression_id が指定されている (修正時)
        sintyoku = get_object_or_404(Sintyoku, pk=sintyoku_id)
    else:               # impression_id が指定されていない (追加時)
        sintyoku = Sintyoku()

    if request.method == 'POST':
        form = SintyokuForm(request.POST, instance=sintyoku)      # POST された request データからフォームを作成
        if form.is_valid():    # フォームのバリデーション
            sintyoku = form.save(commit=False)
            sintyoku.sintyoku = anken  # この感想の、親の書籍をセット
            sintyoku.save()
            anken.kousinjikoku = timezone.datetime.now()
            anken.save()
            return redirect('cms:sintyoku_list', anken_id=anken_id)
    else:    # GET の時
        form = SintyokuForm(instance=sintyoku)  # impression インスタンスからフォームを作成

    return render(request,
                  'cms/sintyoku_edit.html',
                  dict(form=form, anken_id=anken_id, sintyoku_id=sintyoku_id))


def sintyoku_del(request, anken_id, sintyoku_id):
    """感想の削除"""
    sintyoku = get_object_or_404(Sintyoku, pk=sintyoku_id)
    sintyoku.delete()
    return redirect('cms:sintyoku_list', anken_id=anken_id)


class TodoListView(generic.ListView):
    model = Todo
    paginate_by = 5


class TodoCreateView(generic.CreateView):
    model = Todo
    form_class = TodoForm



def task_edit(request, anken_id, task_id=None):
    """タスクの編集"""
    anken = get_object_or_404(Anken, pk=anken_id)  # 親の書籍を読む
    if task_id:   # task_id が指定されている (修正時)
        task = get_object_or_404(Task, pk=task_id)
    else:               # task_id が指定されていない (追加時)
        task = Task()

    if request.method == 'POST':
        form = TaskForm(request.POST, instance=task)      # POST された request データからフォームを作成
        if form.is_valid():    # フォームのバリデーション
            task = form.save(commit=False)
            task.anken = anken  # この感想の、親の書籍をセット
            task.save()
            anken.kousinjikoku = timezone.datetime.now()
            anken.save()
            return redirect('cms:task', anken_id=anken_id)
    else:    # GET の時
        form = TaskForm(instance=task)  # impression インスタンスからフォームを作成

    return render(request,
                  'cms/task_edit.html',
                  dict(form=form, anken_id=anken_id, task_id=task_id))

cms/templates/cms/anken_edit.html
{% extends "cms/base_top.html" %}
{% load bootstrap4 %}


{% block title %}案件編集{% endblock title %}

{% block content %}
<div class="container">
    <h4 class="mt-4 mb-5 border-bottom">案件編集</h4>
    {% if anken_id %}
    <form action="{% url 'cms:anken_mod' anken_id=anken_id %}" method="post">
    {% else %}
    <form action="{% url 'cms:anken_add' %}" method="post">
    {% endif %}
      {% csrf_token %}
      {% bootstrap_form form layout='horizontal' %}
      <div class="form-group row">
        <div class="offset-md-3 col-md-9">
          <button type="submit" class="btn btn-primary">登録</button>
          <a href="{% url 'cms:anken_list' %}" class="btn btn-secondary">戻る</a>
        </div>
      </div>
    </form>
    </form>
</div>
{% endblock content %}

cms/templates/cms/anken_list.html
{% extends "cms/base_top.html" %}
{% load humanize %}

{% block title %}案件一覧{% endblock title %}

{% block head %}

{% endblock head %}



{% block content %}
<div class="content-header">
      <div class="container-fluid">
        <div class="row mb-1">
          <div class="col-sm-6">
            <h1 class="m-0 text-dark">Projects</h1>
            <a href="{% url 'cms:anken_add' %}" class="btn btn-primary btn-sm my-3 origin-color">案件追加</a>
    <a href="{% url 'cms:archiveanken_list' %}" class="btn btn-primary btn-sm my-3 origin-color">過去案件</a>
    <a href="{% url 'cms:weekanken_list' %}" class="btn btn-primary btn-sm my-3 origin-color">1Week案件</a>
    <from action="#">
  <input type="text" name="search" value="" id="id_search" />
</from>
          </div><!-- /.col -->
          <div class="col-sm-6">
            <ol class="breadcrumb float-sm-right">
              <li class="breadcrumb-item"><a href="{% url 'cms:top' %}">Home</a></li>
              <li class="breadcrumb-item active">Projects</li>
            </ol>
          </div><!-- /.col -->
        </div><!-- /.row -->
      </div><!-- /.container-fluid -->
    </div>


<div class="container-fluid">
 

    <table id="table" class="table table-striped table-bordered table-hover tablesorter origin-color">
      <thead>
        <tr>
          <!--<th scope="col">ID</th>-->
          <th scope="col">E/U</th>
          <th scope="col">販社</th>
          <th scope="col">プロダクト</th>
          <th scope="col">SI推進</th>
          <th scope="col">受注時期</th>
          <th scope="col">金額</th>
          <th scope="col">確度</th>
            <th scope="col">状況</th>
          <!--<th scope="col">更新時刻</th>-->
        </tr>
      </thead>
      <tbody>
        {% for anken in ankens %}
        <tr data-href="{% url 'cms:sintyoku_list' anken_id=anken.id %}">
          <!--<th scope="row">{{ anken.id }}</th>-->
          <td>{{ anken.enduser }}</td>
          <td>{{ anken.hansha }}</td>
          <td>{{ anken.product }}</td>
          <td>{{ anken.sisuisin }}</td>
          <td>{{ anken.jutyu }}</td>
          <td>売上：{{ anken.mitumorigaku|intcomma }}円<br>粗利：{{ anken.arari|intcomma }}円</td>
          <td>{{ anken.kakudo }}</td>
          <td>{{ anken.joukyo }}</td>

          <!--<td>{{ anken.kousinjikoku }}</td>-->

        </tr>
        {% endfor %}
      </tbody>
    </table>
</div>




<!--
{# 削除を確認するモーダル ダイアログ #}
    <div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="deleteModalLabel" aria-hidden="true">
      <div class="modal-dialog" role="document">
        <div class="modal-content">
          <div class="modal-header">
            <h5 class="modal-title" id="deleteModalLabel">確認</h5>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
          </div>
          <div class="modal-body">
            <p>ID: <span id="del_pk"></span> を削除しますか？</p>
          </div>
          <div class="modal-footer">
            <a href="#" class="btn btn-primary" id="del_url">OK</a>
            <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
          </div>
        </div>
      </div>
    </div>
{% endblock content %}

-->
{% block extra_js %}
<script>
$(function() {

  //data-hrefの属性を持つtrを選択しclassにclickableを付加
  $('tr[data-href]').addClass('clickable')

    //クリックイベント
    .click(function(e) {

      //e.targetはクリックした要素自体、それがa要素以外であれば
      if(!$(e.target).is('a')){

        //その要素の先祖要素で一番近いtrの
        //data-href属性の値に書かれているURLに遷移する
        window.location = $(e.target).closest('tr').data('href');}
  });
});

$(function(){
   $("#table").tablesorter(
      {
       theme: 'blue'
      });
});


$(function () {
  $('input#id_search').quicksearch('table tbody tr');
});


</script>
{% endblock %}

cms/templates/cms/archiveanken_list.html
{% extends "cms/base_top.html" %}

{% block title %}アーカイブ案件一覧{% endblock title %}

{% block content %}
<div class="container-fluid">
    <h4 class="mt-1 border-bottom">アーカイブ案件一覧</h4>
    <!--<a href="{% url 'cms:anken_add' %}" class="btn btn-primary btn-sm my-3">追加</a>-->
    <!--<a href="{% url 'cms:anken_list' %}" class="btn btn-primary btn-sm my-3">過去案件</a>-->
    <table class="table table-striped table-bordered table-hover ">
      <thead>
        <tr>
          <!--<th scope="col">ID</th>-->
          <th scope="col">E/U</th>
          <th scope="col">販社</th>
          <th scope="col">プロダクト</th>
          <th scope="col">SI推進</th>
          <th scope="col">受注時期</th>
          <th scope="col">導入時期</th>
          <th scope="col">確度</th>
          <th scope="col">操作</th>
        </tr>
      </thead>
      <tbody>
        {% for anken in ankens %}
        <tr data-href="{% url 'cms:sintyoku_list' anken_id=anken.id %}">
          <!--<th scope="row">{{ anken.id }}</th>-->
          <td>{{ anken.enduser }}</td>
          <td>{{ anken.hansha }}</td>
          <td>{{ anken.product }}</td>
          <td>{{ anken.sisuisin }}</td>
          <td>{{ anken.jutyu }}</td>
          <td>{{ anken.donyu }}</td>
          <td>{{ anken.kakudo }}</td>
          <td>
            <a href="{% url 'cms:anken_mod' anken_id=anken.id %}" class="btn btn-outline-primary btn-sm">修正</a>
            <a href="{% url 'cms:anken_del' anken_id=anken.id %}" class="btn btn-outline-danger btn-sm del_confirm">削除</a>
            <!--<a href="{% url 'cms:anken_archive' anken_id=anken.id %}" class="btn btn-outline-danger btn-sm del_confirm">アーカイブ</a>-->
            <!--
            <button class="btn btn-outline-danger btn-sm del_confirm" data-toggle="modal" data-target="#deleteModal" data-pk="{{ anken.id }}" data-url="{% url 'cms:anken_del' anken_id=anken.id %}">削除確認</button>
            -->
            <a href="{% url 'cms:sintyoku_list' anken_id=anken.id %}" class="btn btn-outline-info btn-sm">進捗</a>
            <a href="{% url 'cms:anken_archiveback' anken_id=anken.id %}" class="btn btn-outline-info btn-sm">案件復帰</a>
          </td>

        </tr>
        {% endfor %}
      </tbody>
    </table>
  <a href="{% url 'cms:anken_list' %}" class="btn btn-secondary btn-sm">案件一覧</a>
</div>



<!--
{# 削除を確認するモーダル ダイアログ #}
    <div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="deleteModalLabel" aria-hidden="true">
      <div class="modal-dialog" role="document">
        <div class="modal-content">
          <div class="modal-header">
            <h5 class="modal-title" id="deleteModalLabel">確認</h5>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
          </div>
          <div class="modal-body">
            <p>ID: <span id="del_pk"></span> を削除しますか？</p>
          </div>
          <div class="modal-footer">
            <a href="#" class="btn btn-primary" id="del_url">OK</a>
            <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
          </div>
        </div>
      </div>
    </div>
{% endblock content %}

-->
{% block extra_js %}
<script>
$(function() {

  //data-hrefの属性を持つtrを選択しclassにclickableを付加
  $('tr[data-href]').addClass('clickable')

    //クリックイベント
    .click(function(e) {

      //e.targetはクリックした要素自体、それがa要素以外であれば
      if(!$(e.target).is('a')){

        //その要素の先祖要素で一番近いtrの
        //data-href属性の値に書かれているURLに遷移する
        window.location = $(e.target).closest('tr').data('href');}
  });
  });

</script>
{% endblock %}

cms/templates/cms/sintyoku_list.html
{% extends "cms/base_top.html" %}
{% load humanize %}

{% block title %}進捗{% endblock title %}

{% block sidebar %}
<h6 class="sidebar-heading d-flex justify-content-between align-items-center px-3 mt-4 mb-1 text-muted">
  <span>Todo</span>
  <a class="d-flex align-items-center text-muted" href="#">
    <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-plus-circle"><circle cx="12" cy="12" r="10"></circle><line x1="12" y1="8" x2="12" y2="16"></line><line x1="8" y1="12" x2="16" y2="12"></line></svg>
  </a>
</h6>
<div class="row">
  <div class="col-md-2">
    ○
  </div>
  <div class="col-md-7">
    タスクーーーーーーーーーーーーーーー
  </div>
  <div class="col-md-3">
    3/10
  </div>
</div>




{% endblock sidebar%}

{% block content %}
<div class="container-fluid">
    <h4 class="mt-4 border-bottom">進捗 <small class="text-muted ml-3"></small></h4>
    <div class="row">
      <div class="col-md-10">
        <a href="{% url 'cms:anken_list' %}" class="btn btn-secondary btn-sm">案件一覧</a>
        <a href="{% url 'cms:anken_mod' anken_id=anken.id %}" class="btn btn-secondary btn-sm">案件修正</a></p>
      </div>
      <div class="col-md-2">
        <a href="{% url 'cms:anken_archive' anken_id=anken.id %}" class="btn btn-outline-danger btn-sm del_confirm">案件アーカイブ</a>
        <a href="{% url 'cms:anken_del' anken_id=anken.id %}" class="btn btn-outline-danger btn-sm del_confirm">案件削除</a>

      </div>
    </div>
  

<table class="table">
            <thead style="background-color: #ddd;">
              <tr>
                <th>エンドユーザー</th>
                <th>販社</th>
                <th>プロダクト</th>
                <th>SBKKトスアップ</th>
                <th>受注時期</th>
                <th>導入時期</th>

              </tr>
            </thead>
            <tbody>
              <tr class="odd">
                <td>{{ anken.enduser }}</td>
                <td>{{ anken.hansha  }}</td>
                <td>{{ anken.product }}</td>
                <td>{{ anken.sbkk }}</td>
                <td>{{ anken.jutyu }}</td>
                <td>{{ anken.donyu }}</td>

              </tr>
              
            </tbody>
           </table><!--/END First Table -->
       
       <table class="table">
            <thead style="background-color: #ddd;">
              <tr>
                <th>受注金額</th>
                <th>粗利</th>
                <th>状況</th>
                <th>競合</th>
                

              </tr>
            </thead>
            <tbody>
              <tr class="odd">
                <td>{{ anken.mitumorigaku|intcomma }}円</td>
                <td>{{ anken.arari|intcomma  }}円</td>
                <td>{{ anken.joukyo }}</td>
                <td>{{ anken.kyougou }}</td>
                
              </tr>
              
            </tbody>
           </table><!--/END First Table -->
       

<div class="row">
      <div class="col-md-12">
        <a href="{% url 'cms:sintyoku_add' anken_id=anken.id %}" class="btn btn-primary btn-sm my-3">進捗追加</a>
        
    </div>
</div>
  


  <table class="table table-striped table-bordered">
      <thead>
        <tr>
          <th style="width:20%">記入日</th>
          <th style="width:60%">進捗</th>
          <th style="width:20%">操作</th>
        </tr>
      </thead>
      <tbody>
        {% for sintyoku in sintyokus %}
        <tr>
          <td>{{ sintyoku.kinyubi }}</td>
          <td>{{ sintyoku.shosai|linebreaksbr }}</td>
          <td>
            <a href="{% url 'cms:sintyoku_mod' anken_id=anken.id sintyoku_id=sintyoku.id %}" class="btn btn-outline-primary btn-sm">修正</a>
            <button class="btn btn-outline-danger btn-sm del_confirm" data-toggle="modal" data-target="#deleteModal" data-pk="{{ sintyoku.id }}" data-url="{% url 'cms:sintyoku_del' anken_id=anken.id sintyoku_id=sintyoku.id %}">削除</button>
          </td>
        </tr>
        {% endfor %}
      </tbody>
    </table>

</div>

{% if is_paginated %}
    <nav aria-label="Page navigation">
      <ul class="pagination">
        {% if page_obj.has_previous %}
          <li class="page-item"><a class="page-link" href="?page={{ page_obj.previous_page_number }}" aria-label="Previous"><span aria-hidden="true">&laquo;</span><span class="sr-only">Previous</span></a></li>
        {% else %}
          <li class="page-item disabled"><a class="page-link" href="#" aria-label="Previous"><span aria-hidden="true">&laquo;</span><span class="sr-only">Previous</span></a></li>
        {% endif %}
        {% for linkpage in page_obj.paginator.page_range %}
          {% ifequal linkpage page_obj.number %}
            <li class="page-item active"><a class="page-link" href="#">{{ linkpage }}</a></li>
          {% else %}
            <li class="page-item"><a class="page-link" href="?page={{ linkpage }}">{{ linkpage }}</a></li>
        {% endifequal %}
        {% endfor %}
        {% if page_obj.has_next %}
          <li class="page-item"><a class="page-link" href="?page={{ page_obj.next_page_number }}" aria-label="Next"><span aria-hidden="true">&raquo;</span><span class="sr-only">Next</span></a></li>
        {% else %}
          <li class="page-item disabled"><a class="page-link" href="#" aria-label="Next"><span aria-hidden="true">&raquo;</span><span class="sr-only">Next</span></a></li>
        {% endif %}
      </ul>
    </nav>
    {% endif %}



  {# 削除を確認するモーダル ダイアログ #}
    <div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="deleteModalLabel" aria-hidden="true">
      <div class="modal-dialog" role="document">
        <div class="modal-content">
          <div class="modal-header">
            <h5 class="modal-title" id="deleteModalLabel">確認</h5>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
          </div>
          <div class="modal-body">
            <p>ID: <span id="del_pk"></span> を削除しますか？</p>
          </div>
          <div class="modal-footer">
            <a href="#" class="btn btn-primary" id="del_url">OK</a>
            <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
          </div>
        </div>
      </div>
    </div>
{% endblock content %}

{% block extra_js %}
<script>
$(function() {
  $('.del_confirm').on('click', function () {
     $("#del_pk").text($(this).data("pk"));
     $('#del_url').attr('href', $(this).data("url"));
  });
});
</script>
{% endblock %}